"""Pydantic schema for the structured knowledge layer (stage 3).

Four item types are extracted from the tools' md files:
decisions, rules, warnings, changes. Each item keeps a source reference
back to the exact tool + file it came from.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

ItemType = Literal["decisions", "rules", "warnings", "changes"]


class SourceRef(BaseModel):
    tool: str = ""
    file: str = ""
    anchor: Optional[str] = Field(
        default=None, description="Nearest markdown heading the item appeared under"
    )


class Decision(BaseModel):
    """A technical decision that was made (what was chosen and why)."""

    id: str = ""
    title: str = Field(description="Short name of the decision")
    summary: str = Field(description="What was decided and why, one or two sentences")
    tags: list[str] = Field(default_factory=list, description="Topic tags, e.g. db, ui, images")
    observed_at: Optional[str] = Field(
        default=None, description="ISO date the decision was made, if stated in the text"
    )
    source: SourceRef = Field(default_factory=SourceRef)


class Rule(BaseModel):
    """A standing instruction / convention that must be followed."""

    id: str = ""
    rule: str = Field(description="The rule itself, phrased as an instruction")
    scope: str = Field(default="", description="Where it applies: ui, db, api, security, ...")
    notes: str = Field(default="", description="Exceptions or clarifications")
    observed_at: Optional[str] = None
    source: SourceRef = Field(default_factory=SourceRef)


class WarningItem(BaseModel):
    """A sensitive/fragile area flagged as 'be careful' or 'do not touch'."""

    id: str = ""
    area: str = Field(description="The component or area at risk")
    message: str = Field(description="What must not be done / what breaks")
    severity: Literal["low", "medium", "high"] = "medium"
    observed_at: Optional[str] = None
    source: SourceRef = Field(default_factory=SourceRef)


class ChangeRecord(BaseModel):
    """A concrete change to the system: schema, API, config, structure."""

    id: str = ""
    area: str = Field(description="What changed: table/endpoint/component name")
    description: str = Field(description="What was added/removed/modified")
    change_type: Literal["added", "removed", "modified"] = "modified"
    observed_at: Optional[str] = None
    source: SourceRef = Field(default_factory=SourceRef)


class ExtractedItems(BaseModel):
    """What the LLM returns for a single file (sources/ids are filled in later)."""

    decisions: list[Decision] = Field(default_factory=list)
    rules: list[Rule] = Field(default_factory=list)
    warnings: list[WarningItem] = Field(default_factory=list)
    changes: list[ChangeRecord] = Field(default_factory=list)


class StructuredQuerySpec(BaseModel):
    """A query against the structured store, generated by the LLM from the question."""

    item_types: list[ItemType] = Field(
        default_factory=list, description="Which item types to search; empty = all types"
    )
    keywords: list[str] = Field(
        default_factory=list,
        description="Free-text terms to match (Hebrew or English); empty = no text filter",
    )
    tags: list[str] = Field(default_factory=list, description="Tag/scope/area filters")
    date_from: Optional[str] = Field(
        default=None, description="ISO date — only items observed on/after this date"
    )
    date_to: Optional[str] = Field(
        default=None, description="ISO date — only items observed on/before this date"
    )
    latest_only: bool = Field(
        default=False, description="True when the user asks for the current/latest state"
    )
    limit: int = 50


class RouteDecision(BaseModel):
    route: Literal["semantic", "structured"]
    reason: str = ""
